### ISSUE TITLE
.exe can't be opened on my Windows 10

### ISSUE THREAD

**Issue by PeppoLS** [JeFaisDesSpaghettis/mh3se#1]
Hello, I downloaded and extracted the mh3se-v090 folder on my PC but when I try to open it it simply doesn't. I turned off my antivirus because that's usually the problem but in this case, I still couldn't open the .exe. I also tried to run it as administrator but nothing changed. How can I try to open it in another way? Thanks!

**Comment by JeSuisSurGithub** [comment]
It's a non-interactive command line program:
1. You need to open windows cmd: `Windows + R` -> write `cmd` -> `Enter`
2. Navigate to the folder type in: `cd [path to the folder]`, most likely `C:\Users\[your username]\Downloads\mh3se-v090`
3. Then you can enter the commands given in the [guide](https://github.com/JeFaisDesSpaghettis/mh3se/blob/main/README.md#usage)

**Comment by JeSuisSurGithub** [comment]
I added a guided mode (now it will stay open when you start it from the file explorer and not disappear) in the [new version](https://github.com/JeFaisDesSpaghettis/mh3se/releases/tag/0.10.0), if that can help
